print("enter 3 number")
num1=int(input("enter the first number"))
num2=int(input("enter the second number"))
num3=int(input("enter the third number"))
largest =max(num1,num2,num3)
print("the greater number is",largest)
